# Generated by Django 5.0.4 on 2024-05-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kant',
            name='image_blind',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kant',
            name='image_textile',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='textile',
            name='image_blind',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='textile',
            name='image_textile',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
