server {
    listen 80;
    server_name localhost;

    # Если запрос начинается на /static/, Nginx ищет файл в папке /app/static/
    location /static/ {
        alias /app/static/;
    }

    # Все остальные запросы перенаправляем на Gunicorn (сервис web)
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}