# Generated by Django 4.1.1 on 2024-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rome_blind',
            name='side_chain',
            field=models.CharField(choices=[('1', 'Слева'), ('2', 'Справа')], default='1', max_length=10),
        ),
    ]
